version: "3.8"
services:
  cyberchef:
    build: ./cyberchef
    hostname: cyberchef
    container_name: cyberchef
    image: mbopm/cyberchef
    platform: linux/amd64
    ports:
      - "127.0.0.1:8080:80"